universe   = vanilla
executable = run_cmssw.sh
arguments  = root://cms-xrd-global.cern.ch//store/data/Run2025C/L1Scouting/L1SCOUT/v1/000/392/526/00001/e844cd3e-8d8e-424b-b1f7-d45e0480d977.root /eos/home-d/dmbelyts/root_out3/392526/part_19/392526_991.root
output     = logs/job_991.out
error      = logs/job_991.err
log        = logs/job_991.log
+JobFlavour = "longlunch"

+AccountingGroup = "group_u_CMS.CAF.COMM"

transfer_input_files = /afs/cern.ch/user/d/dmbelyts/CMSSW_15_0_6/src/Demo/analyzer_demo/python/demo_cfg.py


use_x509userproxy = true
x509userproxy = /afs/cern.ch/user/d/dmbelyts/CMSSW_15_0_6/src/Demo/analyzer_demo/proxy.pem

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue 1
