universe   = vanilla
executable = run_cmssw.sh
arguments  = root://cms-xrd-global.cern.ch//store/data/Run2025C/L1Scouting/L1SCOUT/v1/000/392/526/00001/8f91c03f-fbd2-408a-9df4-258102fb4f61.root /eos/home-d/dmbelyts/root_out3/392526/part_19/392526_964.root
output     = logs/job_964.out
error      = logs/job_964.err
log        = logs/job_964.log
+JobFlavour = "longlunch"

+AccountingGroup = "group_u_CMS.CAF.COMM"

transfer_input_files = /afs/cern.ch/user/d/dmbelyts/CMSSW_15_0_6/src/Demo/analyzer_demo/python/demo_cfg.py


use_x509userproxy = true
x509userproxy = /afs/cern.ch/user/d/dmbelyts/CMSSW_15_0_6/src/Demo/analyzer_demo/proxy.pem

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue 1
