universe   = vanilla
executable = run_cmssw.sh
arguments  = root://cms-xrd-global.cern.ch//store/data/Run2025C/L1Scouting/L1SCOUT/v1/000/392/526/00001/db77a078-9306-43e7-8201-c876db2f654b.root /eos/home-d/dmbelyts/root_out3/392526/part_18/392526_939.root
output     = logs/job_939.out
error      = logs/job_939.err
log        = logs/job_939.log
+JobFlavour = "longlunch"

+AccountingGroup = "group_u_CMS.CAF.COMM"

transfer_input_files = /afs/cern.ch/user/d/dmbelyts/CMSSW_15_0_6/src/Demo/analyzer_demo/python/demo_cfg.py


use_x509userproxy = true
x509userproxy = /afs/cern.ch/user/d/dmbelyts/CMSSW_15_0_6/src/Demo/analyzer_demo/proxy.pem

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue 1
